// 2026-05-22 Phase 1 team-distribution-roadmap:barrel auto-generated by scripts/gen-design-system-barrel.mjs
// Re-export 主元件 / patterns / hooks / lib(consumers can also use subpath imports per package.json exports map)

// ─── Components ───────────────────────────────────────────────────────────
export * from './components/Accordion/index'
export * from './components/Alert/index'
export * from './components/AppShell/index'
export * from './components/AspectRatio/index'
export * from './components/Avatar/index'
export * from './components/Badge/index'
export * from './components/Breadcrumb/index'
export * from './components/BulkActionBar/index'
export * from './components/Button/index'
export * from './components/Calendar/index'
export * from './components/Carousel/index'
export * from './components/Chart/index'
export * from './components/Checkbox/index'
export * from './components/Chip/index'
export * from './components/CircularProgress/index'
export * from './components/Coachmark/index'
export * from './components/Combobox/index'
export * from './components/DataTable/index'
export * from './components/DatePicker/index'
export * from './components/DescriptionList/index'
export * from './components/Dialog/index'
export * from './components/DropdownMenu/index'
export * from './components/Empty/index'
export * from './components/Field/index'
export * from './components/FieldControlGroup/index'
export * from './components/FileItem/index'
export * from './components/FileUpload/index'
export * from './components/FileViewer/index'
export * from './components/Input/index'
export * from './components/LinkInput/index'
export * from './components/NumberInput/index'
export * from './components/PeoplePicker/index'
export * from './components/Popover/index'
export * from './components/ProgressBar/index'
export * from './components/RadioGroup/index'
export * from './components/Rating/index'
export * from './components/ScrollArea/index'
export * from './components/SegmentedControl/index'
export * from './components/Select/index'
export * from './components/Separator/index'
export * from './components/Sheet/index'
export * from './components/Sidebar/index'
export * from './components/Skeleton/index'
export * from './components/Slider/index'
export * from './components/Steps/index'
export * from './components/Switch/index'
export * from './components/Tabs/index'
export * from './components/Tag/index'
export * from './components/Textarea/index'
export * from './components/TimePicker/index'
export * from './components/Toast/index'
export * from './components/Tooltip/index'
export * from './components/TreeView/index'

// ─── Patterns ─────────────────────────────────────────────────────────────
export * from './patterns/element-anatomy/index'
export * from './patterns/header-canonical/index'
export * from './patterns/resize-handle/index'

// ─── Internal(subpath-only,排除 root front-door per dim-72 SSOT)─────────────
// 下列 internal 元件/pattern 不在 root barrel front-door;只能 subpath import
// (@qijenchen/design-system/{components,patterns}/<Dir>),「包裝後 + 自行確認」才可用。
// SSOT = 各自 spec.md frontmatter isInternal。改公開/內部請改 frontmatter 後重跑本 generator。
//   - components/Command
//   - components/DateGrid
//   - components/HoverCard
//   - components/Menu
//   - components/Notice
//   - components/OverflowIndicator
//   - components/ProfileCard
//   - components/SelectMenu
//   - components/SelectionControl
//   - patterns/horizontal-overflow
//   - patterns/overlay-surface

// ─── Hooks ────────────────────────────────────────────────────────────────
export * from './hooks/use-controllable'
export * from './hooks/use-is-narrow-viewport'
export * from './hooks/use-is-touch-device'
export * from './hooks/use-overflow-items'

// ─── Lib utilities ────────────────────────────────────────────────────────
export * from './lib/drag-visual'
export * from './lib/multi-select-ordering'
export * from './lib/utils'
