// AUTO-GENERATED by scripts/gen-component-indexes.mjs — DO NOT EDIT MANUALLY.
// Re-export pattern enables package.json exports map subpath:
//   import { ... } from '@qijenchen/design-system/{components,patterns}/<Dir>'
// Regenerate: node scripts/gen-component-indexes.mjs
export * from './profile-card'
